drips-network/app

src/routes/+layout.svelte

Automatically enables the Radicle Design System's dark mode depending on system-level user preference.

feat: Auto dark mode

---

package-lock.json
package.json
src/lib/components/connect-button/connect-button.svelte
src/lib/stores/tokens/index.ts
src/lib/stores/tokens/stored-custom-tokens.ts
src/lib/stores/tokens/tokens.store.ts
src/lib/stores/tokens/tokens.store.unit.test.ts
src/lib/utils/assert.ts

Adds a new store that serves Uniswap's default token list for a given chain, and allows adding, removing and banning/unbanning custom tokens, which are persisted in localstorage.
Closes #13

feat: tokens store

---

package-lock.json
src/lib/components/section-skeleton/section-skeleton.svelte
src/lib/components/splits-table/splits-table-split-lozenge.svelte
src/lib/components/splits-table/splits-table-split.svelte
src/lib/components/splits-table/splits-table-vertical-line.svelte
src/lib/components/splits-table/splits-table.svelte
src/lib/components/splits-table/types.ts
src/lib/stores/splits/methods/pretty-split-percent.ts
src/lib/stores/splits/types.ts
src/routes/dashboard/+page.svelte
src/routes/dashboard/sections/splits.section.svelte
src/styles/app.css

- styled like Figma
- no store / fetches inside component based on userId prop (so we can use the section on profiles)
- updated Dashboard to handle wallet-account changes
new to typescript + svelte so all feedback appreciated!
closes #23

add Splits Section to Dashboard, closes #23

---

package-lock.json
package.json

Includes fixes for relative Twemoji paths and faulty imports in `SegmentedControl`

chore: update radicle-design-system dep

---

src/lib/components/amount/amount.svelte

Fixes unnecessary polarity signs appearing in amount component.

fix: double minus

---

src/lib/components/avatar/avatar.svelte
src/lib/components/splits-table/splits-table-split.svelte
src/lib/components/splits-table/splits-table.svelte
src/lib/components/splits-table/types.ts
src/routes/app/dashboard/sections/splits.section.svelte

just a small update to add IdentityBadge / profile link to current splits table

add IdentityBadge to splits table

---

package-lock.json
package.json
src/lib/components/stepper/__test__/stepper.unit.test.ts
src/lib/components/stepper/stepper.svelte
src/lib/components/toggle/toggle.svelte
src/lib/components/toggleable/toggleable.svelte
src/lib/flows/create-stream-flow/input-details.svelte
src/lib/flows/create-stream-flow/methods/combine-date-and-time.ts
src/lib/flows/create-stream-flow/methods/create-stream.ts
src/lib/flows/create-stream-flow/methods/parse-date.ts
src/lib/flows/create-stream-flow/methods/parse-time.ts
src/lib/flows/top-up-flow/trigger-top-up-transaction.svelte
src/lib/flows/withdraw-flow/enter-amount.svelte
src/lib/stores/balances/utils/estimate.ts
src/lib/stores/streams/metadata.ts
src/lib/stores/streams/methods/build-asset-configs.ts
src/routes/app/[userId]/tokens/[token]/+page.svelte
src/routes/app/[userId]/tokens/[token]/streams/[dripId]/+page.svelte

Resolves #47 
Adds the ability to create scheduled streams with set start- and end dates.
Merge after #123

feat: scheduled streams

---

src/lib/components/input-address/input-address.svelte
src/lib/stores/ens/ens.store.ts

fix: input-address ens lookup resolves #132

---

src/lib/components/search-bar/search-bar.svelte

fix: search not losing focus while tabbing

---

src/lib/components/identity-card/identity-card.svelte

fix: mangled tap target on identity card

---

src/lib/flows/collect-flow/collect-amounts.svelte

fix: 'splitting 0'

---

src/lib/components/account-menu/account-menu.svelte
src/lib/components/copyable/copyable.svelte
src/lib/components/identity-badge/identity-badge.svelte
src/lib/components/tooltip/tooltip.svelte

fix: cannot select ens name on profile

---

src/routes/+page.svelte
src/routes/components/hero-section.svelte

Remove the pixelated font animation on hover.
Signed-off-by: Brandon Oxendine <brandon.oxendine@gmail.com>

fix: remove font hover animation code

---

src/lib/flows/create-stream-flow/input-details.svelte

feat: pre-select first token in create stream modal

---

src/lib/components/section-skeleton/section-skeleton.svelte

fix: scaled down sections

---

src/lib/components/section-skeleton/section-skeleton.svelte

Resolves #184 together w/ #185

fix: glitchy scrollbar when scaling down section skeleton

---

package-lock.json
src/lib/components/fit-text/fit-text.svelte
src/lib/components/token/token.svelte
src/lib/utils/seeded-random-element.ts
src/routes/app/[userId]/tokens/[token]/+page.svelte

Adds
- dynamic icons based on symbol + random address-seeded color for tokens with no or broken image URL
- proper question mark icon for completely unknown tokens
- a new `FitText` component that automatically finds a font size for text so that it fits the component's parent container.
- showing both name & symbol on token detail page (not feeling strongly on this one).
See summary here: https://github.com/radicle-dev/drips-app-v2/issues/161#issuecomment-1335513416
Resolves #161

feat: dynamic token icon placeholders

---

src/lib/components/button/button.svelte
src/lib/components/list-select/list-select.svelte
src/lib/components/selected-dot/selected-dot.svelte
src/lib/components/success-step/success-step.svelte
src/lib/flows/collect-flow/collect-amounts.svelte
src/lib/flows/collect-flow/select-token.svelte
src/lib/flows/collect-flow/success.svelte
src/lib/flows/create-stream-flow/input-details.svelte
src/lib/flows/edit-splits-flow/edit-splits-inputs.svelte
src/lib/flows/top-up-flow/approve.svelte
src/lib/flows/top-up-flow/enter-amount.svelte
src/lib/flows/top-up-flow/select-token.svelte
src/lib/flows/withdraw-flow/enter-amount.svelte

feat: primary buttons, more distinct list-select select state

---

src/routes/app/dashboard/sections/balances.section.svelte
src/routes/app/dashboard/sections/streams.section.svelte

fix: Page visibly continuously refreshes behind modal while flows are waiting for subgraph to update

---

src/lib/components/form-field/form-field.svelte
src/lib/components/toggle/toggle.svelte
src/lib/flows/top-up-flow/enter-amount.svelte
src/lib/flows/withdraw-flow/enter-amount.svelte

feat: allow withdrawing and topping up max amount

---

src/lib/components/drips-animation/drips-animation.svelte

fix: drip animation pauses when window loses focus

---

src/lib/flows/create-stream-flow/methods/create-stream.ts
src/lib/utils/random-bigint-until-unique.ts

feat: ensure dripId is unique per asset config

---

src/lib/components/modal-layout/modal-layout.svelte

I think this feels a lot smoother.

feat: tweaked modal transition

---

package-lock.json
src/e2e-tests/helpers/take-screenshot.ts
src/e2e-tests/scripts/setup.sh
src/e2e-tests/top-up-create-stream.e2e.test.ts
src/lib/components/button/button.svelte
src/lib/components/form-field/form-field.svelte
src/lib/components/list-select/list-select.svelte
src/lib/flows/delete-stream-flow/confirm.svelte
src/lib/flows/delete-stream-flow/delete-stream-flow-steps.ts
src/lib/flows/delete-stream-flow/methods/delete-stream.ts
src/lib/flows/top-up-flow/enter-amount.svelte
src/lib/stores/balances/balances.store.ts
src/lib/stores/balances/utils/estimate.ts
src/lib/stores/streams/methods/build-asset-configs.ts
src/routes/app/[userId]/tokens/[token]/streams/[dripId]/+page.svelte
src/routes/app/dashboard/sections/balances.section.svelte

feat: delete stream

---

src/lib/components/padded-horizontal-scroll/padded-horizontal-scroll.svelte
src/lib/components/section-skeleton/section-skeleton.svelte
src/routes/app/dashboard/sections/balances.section.svelte
src/routes/app/dashboard/sections/streams.section.svelte

Fixes the cut-off overflow on horizontally scrolling sections.

fix: horizontal scroll cut off at sides

---

src/lib/flows/edit-stream-flow/edit-stream-flow-steps.ts
src/lib/flows/edit-stream-flow/enter-new-details.svelte
src/routes/app/[userId]/tokens/[token]/streams/[dripId]/+page.svelte

feat: edit stream

---

src/lib/components/focus-trap/focus-trap.svelte
src/lib/components/focus-trap/methods/focus.ts
src/lib/components/modal-layout/modal-layout.svelte
src/lib/components/toggleable/toggleable.svelte
src/lib/flows/create-stream-flow/input-details.svelte

- Traps keyboard focus inside modals
- Allow modal close button to be focussed by keyboard
Resolves #76

feat: trap focus inside modals

---

src/routes/app/settings/+page.svelte

chore: add redaction font credit

---

src/routes/+page.svelte
src/routes/components/hero-section.svelte

Adds beta notice on HP, and a little slide-in animation on first load.

feat: Beta notice on LP

---

src/lib/components/dropdown/dropdown.svelte
src/lib/components/modal-layout/modal-layout.svelte
src/lib/flows/create-stream-flow/input-details.svelte
src/lib/stores/modal/modal.store.ts

Adds a fancy new dropdown component that is keyboard-navigatable and more aligned with the style of the app.
Resolves #78

feat: improved dropdown component

---

src/lib/flows/collect-flow/collect-amounts.svelte
src/lib/flows/delete-stream-flow/confirm.svelte
src/lib/flows/edit-stream-flow/enter-new-details.svelte
src/lib/flows/pause-flow/pause.svelte
src/lib/flows/unpause-flow/unpause.svelte
src/lib/flows/withdraw-flow/enter-amount.svelte

fix: not all tx waiting steps are unhideable

---

src/lib/components/account-menu/account-menu.svelte

feat: #289

---

src/routes/+layout.svelte
src/routes/+page.svelte

Adds a little intro animation to the LP, and also transitions the jarring background color change if the server renders in dark mode but client is in light mode.

feat: smoother LP intro

---

src/lib/flows/top-up-flow/trigger-top-up-transaction.svelte
src/lib/flows/withdraw-flow/enter-amount.svelte
src/lib/stores/balances/balances.store.ts
src/lib/stores/balances/utils/estimate.ts
src/routes/app/[userId]/tokens/[token]/+page.svelte
src/routes/app/[userId]/tokens/[token]/streams/[dripId]/+page.svelte
src/routes/app/dashboard/sections/balances.section.svelte

fix: fix case sensitive tokens

---

.gitignore
package-lock.json
package.json
svelte.config.js

ci: switch to adapter-vercel

---

src/lib/components/form-field/form-field.svelte
src/lib/components/input-address/input-address.svelte
src/lib/components/text-input/text-input.svelte
src/lib/components/transitioned-height/transitioned-height.svelte
src/lib/flows/add-custom-token/enter-details.svelte
src/lib/flows/create-stream-flow/input-details.svelte
src/lib/flows/edit-splits-flow/edit-splits-inputs.svelte
src/lib/flows/edit-stream-flow/enter-new-details.svelte
src/lib/flows/top-up-flow/enter-amount.svelte
src/lib/flows/withdraw-flow/enter-amount.svelte
src/routes/app/component-showcase/+page.svelte

quick PR for making the text input component match the rest of our inputs.

feat: custom text input with matching styles

---

package-lock.json
src/lib/components/identity-badge/identity-badge.svelte

fix: odd font rendering on safari & FF

---

src/lib/components/search-bar/search-bar.svelte

feat: #314

---

src/routes/+error.svelte

Adds custom error page.
Resolves #119

feat: #119

---

src/lib/components/stream-state-badge/stream-state-badge.svelte
src/lib/components/table/cells/name-and-badge-cell.svelte
src/lib/utils/stream-history.ts
src/routes/app/+layout.svelte
src/routes/app/[userId]/tokens/[token]/streams/[dripId]/+page.svelte
src/routes/app/dashboard/sections/streams.section.svelte

feat: state badges on dashboard

---

src/lib/components/input-address/input-address.svelte
src/lib/components/search-bar/search-bar.svelte
src/lib/components/text-input/text-input.svelte

Resolves #359 
Disables auto correct and -capitalize on address inputs and search.

feat: no autocorrect on search, address input

---

package-lock.json
src/lib/components/amount/amount.svelte
src/lib/components/stream-visual/stream-visual.svelte
src/lib/components/toggle/toggle.svelte
src/lib/stores/amt-delta-unit/amt-delta-unit.store.ts
src/lib/stores/tick/tick.store.ts
src/lib/stores/tick/tick.unit.test.ts
src/lib/utils/stored-writable.ts
src/routes/app/settings/+page.svelte
src/routes/app/settings/components/setting.svelte

Adds settings "Amounts per time unit" and "Slow mode". Also adds a handy new "stored-writable" utility for future localstorage preferences.
Resolves #41

feat: slow mode, feat: custom amount delta units

---

src/lib/components/segmented-control/segmented-control.svelte
src/lib/components/toggle/toggle.svelte
src/routes/app/settings/+page.svelte

feat: custom segmented control, drip-shaped toggle

---

src/lib/stores/theme/theme.store.ts
src/routes/+layout.svelte
src/routes/app/+layout.svelte
src/routes/app/settings/+page.svelte

feat: allow customizing primary color

---

src/lib/components/stepper/stepper.svelte
src/lib/flows/top-up-flow/enter-amount.svelte
src/lib/flows/top-up-flow/top-up-flow-steps.ts
src/lib/utils/restorer.ts

feat: #365

---

src/lib/components/global-advisory/global-advisory.svelte
src/lib/components/large-empty-state/large-empty-state.svelte
src/lib/stores/global-advisory/global-advisory.store.ts
src/lib/stores/wallet/safe/is-safe.ts
src/routes/app/+layout.svelte

feat: safe walletconnect warning

---

package-lock.json
package.json
src/lib/utils/RepoDriverUtils.ts
src/lib/utils/__test__/DripListManager.unit.test.ts
src/lib/utils/driplist/DripListManager.ts
src/lib/utils/metadata/MetadataManagerBase.ts
src/lib/utils/metadata/RepoDriverMetadataManager.ts
src/lib/utils/metadata/tests/RepoDriverMetadataManager.unit.test.ts
src/lib/utils/test-utils/RepoDriverUtils.unit.test.ts

Resolves and context 👉 https://github.com/radicle-dev/drips-app-v2/issues/393
And the [meat🥩](https://github.com/radicle-dev/drips-app-v2/pull/447/files#diff-7604ec522e10f22306b0103490b932841b6a20fa644ab627e4aecb1197e53b47) of the changes.

Introduce `DripListManager`

---

src/lib/components/project-badge/project-badge.svelte

https://media.discordapp.net/attachments/1096004153085530253/1105854364490407998/Screenshot_2023-05-10_at_15.48.02.png?width=461&height=620

feat: show forge on project badge

---

src/routes/app/(flows)/claim-project/steps/enter-git-url/enter-git-url.svelte

Resolves https://github.com/radicle-dev/drips-app-v2/issues/500
and https://github.com/radicle-dev/drips-app-v2/issues/537

Fix https missing

---

src/lib/components/project-avatar/project-avatar.svelte
src/lib/utils/metadata/types.ts
src/lib/utils/project/GitProjectService.ts
src/routes/app/(flows)/claim-project/steps/enter-git-url/enter-git-url.svelte
src/routes/app/(flows)/claim-project/steps/poll-subgraph/poll-subgraph.svelte
src/routes/app/(flows)/claim-project/steps/set-splits-and-emit-metadata/set-splits-and-emit-metadata.svelte

resolves https://github.com/radicle-dev/drips-app-v2/issues/536

Projects without metadata as unclaimed

---

src/lib/components/aggregate-fiat-estimate/fiat-estimate-value.svelte
src/lib/components/amount/amount.svelte
src/lib/components/amount/amount.unit.test.ts
src/lib/components/supporters-section/supporters.section.svelte
src/lib/utils/format-token-amount.ts

style: fiat-est + token amount uses en-us locale (closes #386)

---

src/lib/components/stepper/stepper.svelte
src/routes/+page.svelte
src/routes/app/(flows)/funder-onboarding/+page.svelte
src/routes/app/(flows)/funder-onboarding/steps/build-list/build-list.svelte

having Brandon review,
but @efstajas, holler if there's a certain reason the landing page CTAs were opening in a new tab (I've since removed)
closes #659

add 'back' to funder flow (closes #659)

---

src/routes/+page.svelte

Modified copy for feature section, changed from 3x2 card layout to 4x1, removed unused CSS

style: update features section (closes #649)

---

src/lib/components/social-link/social-link.svelte

fix: social-link trailing /, validate URL from ENS data (closes #654)

---

src/lib/flows/edit-project-splits/steps/edit-dependency-list.svelte
src/lib/flows/edit-project-splits/steps/review.svelte
src/lib/utils/driplist/DripListService.ts
src/lib/utils/metadata/schemas/index.ts
src/lib/utils/metadata/schemas/repo-driver/v2.ts
src/lib/utils/metadata/schemas/repo-driver/v3.ts
src/lib/utils/metadata/types.ts
src/lib/utils/project/GitProjectService.ts
src/routes/app/(flows)/claim-project/steps/configure-dependencies/configure-dependencies.svelte

feat: #739

---

src/lib/components/drip-list-badge/drip-list-badge.svelte
src/lib/components/drip-list-card/drip-list-card-representational.svelte
src/lib/components/support-card/support-card.svelte
src/lib/flows/edit-drip-list/add-member/add-drip-list-member-steps.ts
src/lib/flows/edit-drip-list/add-member/steps/select-drip-list.svelte
src/lib/flows/edit-drip-list/edit-members/edit-drip-list-steps.ts
src/lib/flows/edit-drip-list/shared/steps/edit-drip-list.svelte

feat: #712

---

src/lib/components/carousel/carousel.svelte
src/lib/components/drip-list-card/drip-list-card-representational.svelte
src/routes/+layout.svelte
src/routes/app/(app)/+layout.svelte
src/routes/app/(app)/drip-lists/[listId]/+page.svelte
src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte
src/routes/app/(app)/streams/+page.svelte

Makes supporter cards sticky on drip list views & claimed project profile

make support cards sticky

---

src/lib/components/support-card/support-card.svelte
src/lib/components/supporters-section/supporters.section.svelte
src/lib/flows/edit-drip-list/add-member/steps/select-drip-list.svelte
src/routes/app/(app)/drip-lists/[listId]/+page.svelte
src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte

1. add "Stream tokens" button to drip list owner
2. show Connect wallet if user is not connected
3. update card descriptions accordingly
4. show support card on unclaimed projects (#768 )

Ev/support card buttons (closes #768)

---

src/lib/components/header/header.svelte
src/routes/components/lp-header.svelte

no need to wait for other landing page updates right?

remove beta badge from headers

---

src/e2e-tests/top-up-create-stream.e2e.test.ts
src/lib/components/drip-list-editor/drip-list-editor.svelte
src/lib/components/drip-list-members-editor/drip-list-members-editor.svelte
src/lib/components/percentage-editor/percentage-editor.svelte
src/routes/app/(flows)/funder-onboarding/steps/build-list/build-list.svelte

discussion: https://discord.com/channels/1096003917717983252/1169660428545167480

Ev/drip list editor enhancements (closes #766, closes #773, closes #765, closes #714, closes #570)

---

src/lib/flows/create-stream-flow/input-details.svelte

copy: clarify stream token is from drips account in modal (closes #786)

---

src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte

fix: use ShareButton in project claimable funds banner (closes #754)

---

README.md

- remove "new" and "beta" and "v2"
- add discord to readme
closes #792

Update text of README

---

src/lib/components/support-card/support-card.svelte

fix: supporter card: dont show stream option to project owner (closes #798)

---

src/routes/app/(flows)/claim-project/steps/add-ethereum-address/add-ethereum-address.svelte

(instead of "not found" for any error, including mismatched content)

fix: show funding.json mismatch error to user

---

src/routes/+page.svelte
src/routes/app/(app)/[accountId]/+page.svelte

remove links to Drips V1 (closes #783)

---

.env.template
docs/DEVELOPMENT.md
package-lock.json
package.json
src/routes/api/github/[repoUrl]/+server.ts
src/routes/api/github/[repoUrl]/redis.ts
src/routes/app/(app)/projects/(forges)/github/[githubUsername]/[githubRepoName]/+page.server.ts

cache github API responses with Redis

---

src/lib/components/unclaimed-project-card/unclaimed-project-card.svelte

style: hide est value if no claimable tokens (closes #506)

---

src/routes/app/(app)/[accountId]/tokens/[token]/+page.svelte
src/routes/app/(app)/funds/sections/balances.section.svelte

copy: leaner tooltips for incoming/outgoing balances (closes #396)

---

src/styles/app.css

style: custom selection color: bg primary, text bg (closes #420)

---

src/routes/app/(app)/[accountId]/+page.svelte
src/routes/app/(app)/funds/sections/balances.section.svelte
src/routes/app/(app)/funds/sections/streams.section.svelte

* also make all section buttons primary
closes #423

fix: show stream actions on your own profile (closes #423)

---

src/lib/components/splits/components/split/split.svelte

fix: no max-width for projects on drip-list-card (closes #845)

---

src/lib/components/support-card/components/support-buttons.svelte

fix: support card connect-wallet button should be full-width (closes #862)

---

setup-test.js
src/e2e-tests/top-up-create-stream.e2e.test.ts
src/lib/components/aggregate-fiat-estimate/fiat-estimate-value.svelte
src/lib/components/collect-button/collect-button.svelte
src/lib/components/header/header.svelte
src/lib/components/header/header.unit.test.ts
src/lib/components/list-select/list-select.svelte
src/lib/components/list-select/list-select.types.ts
src/lib/components/success-step/success-step.svelte
src/lib/flows/global-collect-flow/batch-collect.ts
src/lib/flows/global-collect-flow/global-collect-flow-steps.ts
src/lib/flows/global-collect-flow/steps/select-tokens/components/add-custom-token-button.svelte
src/lib/flows/global-collect-flow/steps/select-tokens/select-tokens.svelte
src/routes/app/(app)/[accountId]/tokens/[token]/+page.svelte
src/routes/app/(app)/component-showcase/+page.svelte
src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte
src/routes/app/(app)/projects/+page.svelte
src/routes/app/+layout.svelte

feat: global collect button, fix: #846

---

src/lib/components/supporters-section/components/support-item.svelte
src/lib/components/supporters-section/supporters.section.svelte

style: remove big icon in support item row (closes #892)

---

src/lib/components/social-link/social-link.svelte

only (minor) find from scanning the app for external urls.

fix: wrap handle-only ENS record values in buildExternalUrl()

---

.env.template
package-lock.json
package.json
src/e2e-tests/top-up-create-stream.e2e.test.ts
src/lib/components/blog/post-card/post-card.svelte
src/lib/components/developer-section/stream-developer.section.svelte
src/lib/components/edu-card/edu-card.svelte
src/lib/components/header/header.svelte
src/lib/graphql/dripsQL.ts
src/lib/utils/guard-connected.ts
src/lib/utils/total-dripped-approx.ts
src/routes/api/blog/posts/schema.ts
src/routes/api/gql/+server.ts
src/routes/api/tlv/+server.ts
src/routes/app/(app)/+layout.svelte
src/routes/app/(app)/+page.server.ts
src/routes/app/(app)/+page.svelte
src/routes/app/(app)/[accountId]/tokens/[token]/streams/[dripId]/+page.svelte
src/routes/app/(app)/component-showcase/+page.svelte
src/routes/app/(app)/connect/+page.svelte
src/routes/app/(app)/drip-lists/+page.svelte
src/routes/blog/+page.server.ts
src/routes/components/lp-total-dripped-badge.svelte

adds
- explore page at /app
- new developer section for stream detail view

explore page 

---

src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte

A tiny pull request to change some text.
closes #970

change Total donations to just donations 

---

src/styles/colors.css

style: remove transparency from css colors (closes #1009)

---

src/lib/components/drip-lists-section/drip-lists-section.svelte
src/lib/components/projects-section/projects-section.svelte
src/routes/app/(app)/funds/sections/balances.section.svelte
src/routes/app/(app)/funds/sections/streams.section.svelte

closes #902
"normal" style buttons in all 'sections' (profile + dashboard)

style: section buttons normal variant (closes #902)

---

src/routes/+error.svelte

fix: error page button goto /app (closes #899)

---

src/lib/components/drip-list-card/drip-list-card-representational.svelte
src/lib/components/identity-badge/identity-badge.svelte
src/lib/components/pile/pile-presets.ts
src/lib/components/splits/components/split/split.svelte
src/lib/components/user-avatar/user-avatar.svelte
src/lib/flows/create-drip-list-flow/create-drip-list-flow.ts
src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte

closes #887
outline (+background) always applied to user/address avatars

style: user avatar outlined always (closes #887)

---

src/lib/components/table/cells/drip-list-badge.cell.svelte
src/lib/components/table/cells/identity-badge-cell.svelte
src/lib/components/table/table.svelte
src/routes/app/(app)/drip-lists/all/+page.svelte
src/routes/app/(app)/funds/sections/streams.section.svelte

style: add owner column to drip-lists-all table (closes #974)

---

src/lib/components/drip-list-members-editor/drip-list-members-editor.svelte
src/lib/flows/claim-project-flow/steps/configure-dependencies/configure-dependencies.svelte
src/lib/flows/edit-project-splits/edit-project-splits-steps.ts
src/lib/flows/edit-project-splits/steps/edit-dependency-list.svelte
src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte

closes #903 
- fixed in claim project flow
- fixed in edit project splits flow

fix: project cant split to self (closes #903)

---

src/routes/app/(app)/funds/sections/streams.section.svelte

closes #949
your token page
your profile
someone else's profile

copy: better empty text for streams section (closes #949)

---

src/lib/components/collect-button/collect-button.svelte
src/lib/flows/global-collect-flow/steps/select-tokens/select-tokens.svelte

- close #882
- modal content is conditional to can-collect:
**FROM**
**TO:**
_no collectable:_
_collectable:_

style: improve collect modal (closes #882)

---

src/lib/components/annotation-box/annotation-box.svelte
src/lib/components/drip-list-card/components/voting-round-countdown.svelte
src/lib/components/drip-list-card/components/voting-round-notice-card.svelte
src/lib/components/drip-list-card/drip-list-card-thumblink.svelte
src/lib/components/drip-list-card/drip-list-card.svelte
src/lib/components/splits/components/split/split.svelte
src/lib/components/splits/splits.svelte

various visual touchups (see commit list) that style elements based on the current figma designs

Feature/multiplayer  ev/touchups

---

src/lib/components/support-card/components/support-buttons.svelte
src/lib/components/support-card/support-card.svelte
src/lib/components/supporters-section/supporters.section.svelte
src/lib/components/table/cells/user-badge.cell.svelte
src/lib/stores/streams/streams.store.ts
src/routes/app/(app)/[accountId]/tokens/[token]/streams/[dripId]/+page.svelte
src/routes/app/(app)/drip-lists/[listId]/+page.svelte
src/routes/app/(app)/funds/sections/streams.section.svelte

closes #983
- allow any address to stream to drip lists
- add these streams to support table (tag with "You" when they're logged in)

feat: allow anyone to stream to a drip list (closes #983)

---

src/lib/components/search-bar/search.ts
src/lib/flows/claim-project-flow/steps/enter-git-url/enter-git-url.svelte
src/lib/utils/build-repo-url.ts
src/lib/utils/is-valid-git-url.ts
src/routes/app/(app)/projects/(forges)/github/[githubUsername]/[githubRepoName]/+page.server.ts

Fix error 500 when navigating to an invalid project URL. It would previously hit the API, which would throw an assertion error when seeing the invalid URL. I added this check on the frontend side too, and also cleaned up the URL validator utilities.

fix: #1145

---

src/routes/api/github/[repoUrl]/+server.ts
src/routes/app/(app)/projects/(forges)/github/[githubUsername]/[githubRepoName]/+page.server.ts

fix: #1150

---

package-lock.json
package.json
src/lib/components/button/button.svelte
src/lib/components/custom-avatar-upload/custom-avatar-upload.svelte
src/lib/components/drop-zone/drop-zone.svelte
src/lib/components/list-editor/classifiers.ts
src/lib/components/list-editor/components/list-editor-input-error.svelte
src/lib/components/list-editor/components/list-editor-input.svelte
src/lib/components/list-editor/errors.ts
src/lib/components/list-editor/hydrators.ts
src/lib/components/list-editor/list-editor.svelte
src/lib/components/list-editor/types.ts
src/lib/components/list-editor/validators.ts
src/lib/components/stepper/stepper.svelte
src/lib/flows/create-drip-list-flow/create-drip-list-flow.ts
src/lib/flows/create-drip-list-flow/steps/build-list/build-list.svelte
src/lib/flows/create-drip-list-flow/steps/configure-voting-round/configure-voting-round.svelte
src/lib/flows/import-from-csv/components/csv-example.svelte
src/lib/flows/import-from-csv/import-from-csv-steps.ts
src/lib/flows/import-from-csv/upload.svelte
src/lib/utils/csv.ts
src/routes/app/(app)/projects/(forges)/github/[githubUsername]/[githubRepoName]/+page.server.ts

Adds ability to import Drip List recipients and collaborators from CSV. For now, only in Drip List creation flow.
All of the work done by @mhgbrown!
Resolves #1143 
Resolves #1102 
Resolves #1053

Csv import

---

src/routes/api/health/+server.ts

add simple ping endpoint

---

src/lib/stores/wallet/wallet.store.ts

Resolves https://github.com/drips-network/app/issues/1188
To test:
1. Remove Filecoin from metamask if already added.
2. Run the app (filecoin branch).
3. Check that it suggests to add Filecoin.
4. Add and switch to Filecoind (should pop up metamask).
5. Change to another network and ignore the pop up and check that you have the option to just disconnect the wallet.

Unsupported network handling

---

.env.template
src/routes/+page.server.ts
src/routes/legal/+layout.ts

Resolves: https://github.com/drips-network/app/issues/1186

Alternative chains redirects

---

src/lib/components/account-menu/account-menu.svelte
src/lib/components/header/header.svelte
src/lib/components/network-picker/network-picker.svelte
src/lib/stores/wallet/network.ts

Also refactors network config into one object instead of many maps and adds a tiny little animation.

Add network config value for hiding network picker per network

---

src/lib/utils/fiat-estimates/fiat-estimates.ts

fiat conversion for WFIL

---

src/lib/components/stepper/components/transact-step.svelte

Previously, batched transactions (e.g. approve & top-up) would fail to propose to a Safe.
This makes it so that in the case of multiple transactions being proposed to a Safe as a single batch, the user sees only the last one (workaround considering there's only a single interaction required by the user and the timeline expects all items to be resolved individually). It also removes the assertion that prevented batches from going through previously.

fix: unable to submit batch TX to safe

---

src/lib/flows/share/steps/share-url.svelte

This PR fixes the filenames of share modal downloadable images.

1292 improve filename of downloaded share image

---

robots-filecoin.txt
src/routes/app/(app)/+page.svelte

Resolves #1321 
Resolves #1322

Fix: #1321, Fix: #1322

---

README.md

This PR adds an embeddable support button to our README

1346 add embeddable support button to readme

---

src/lib/utils/project/GitProjectService.ts

Resolves: https://github.com/drips-network/app/issues/1352

fix: bug causing error when claiming a project that splits 100% to its dependencies

---

src/lib/flows/claim-project-flow/steps/review/review.svelte
src/lib/stores/wallet/__test__/wallet.store.ts
src/lib/stores/wallet/network.ts
src/lib/utils/settlement-date.ts

This PR updates wording to accurately reflect Filecoin settlement.

Change filecoin settlement to weekly on thursday

---

src/lib/flows/import-from-csv/__test__/data/splits-header-space.csv
src/lib/flows/import-from-csv/__test__/parse-upload.unit.test.ts
src/lib/flows/import-from-csv/parse-upload.ts

This PR trims white space around CSV column values.

1393 trim empty spaces in csv import

---

src/routes/api/gasless/call/+server.ts

It was impossible to claim a project that received funds while unclaimed gaslessly, because the logic was falsely excepting the `split` calls to go to `RepoDriver`, when really they go to `Drips`.

fix: #1394

---

src/lib/flows/global-collect-flow/steps/select-tokens/select-tokens.svelte
src/lib/stores/wallet/network.ts
src/lib/utils/settlement-date.ts

Settlement on Filecoin is actually daily, this shows that in the Collect modal.

show daily filecoin settlement

---

src/routes/(pages)/+page.svelte

Add Bluesky, change Twitter to X

---

src/routes/(pages)/app/(app)/[accountId]/tokens/[token]/streams/[dripId]/+page.svelte

Changes some of the values displayed on the stream page to make them show all relevant data in different situations:
- Adds dedicated "Created at" value that always shows when the stream was created on-chain
- Adds dedicated "Configured start date" and "Configured end date" values that appear if start- and end dates have been set explicitly
- Adds a "Runs / ran out of funds at" value that shows the date when the stream will run out of funds (if any)
- Adds a warning tooltip next to "Configured end date" if the end date is later than when the stream will run out of funds
Resolves #1444

fix: #1444

---

src/lib/flows/create-drip-list-flow/create-drip-list-flow.ts
src/lib/flows/create-drip-list-flow/steps/review-voting-round/review-voting-round.svelte
src/lib/flows/create-drip-list-flow/steps/review/review.svelte

fix: #1488

---

.env.template
Dockerfile
package-lock.json
package.json
src/hooks.client.ts
vite.config.ts

Integrate Faro SDK for privacy-preserving, non-sticky (no cookies), anonymous frontend metric collection to Grafana

Integrate faro SDK

---

src/routes/(pages)/app/(app)/components/recently-claimed-projects.svelte

resolves: https://github.com/drips-network/app/issues/1595

refactor: properly display recent claimed projects

---

src/lib/components/rpgf-schedule-card/components/schedule-item.svelte
src/lib/components/rpgf-schedule-card/rpgf-schedule-card.svelte
src/routes/(pages)/app/(app)/rpgf/rounds/[slugOrId]/settings/schedule/+page.svelte

- Enhance the schedule card with times & timezone to ensure ppl know it's in theirs, also add expandable explainers for each step
- Add a notice explaining to round organizers that they're setting schedule in their local timezone

rpgf timeline improvements
