drips-network/app

package-lock.json, src/lib/components/connect-button/connect-button.svelte, src/lib/stores/drips/drips.store.ts, src/lib/stores/drips/index.ts
Adds a new Drips store that creates instances of all Drips SDK clients and exposes them in its state.
In the future, we may add more drips-related information to the state of this store (such as info about the current cycle), which is why using a store pattern to share these client instances globally makes sense.
=> feat: drips store

.github/workflows/commitlint.yml, .github/workflows/e2e-tests.yml, .github/workflows/unit-tests.yml
Fix GH actions failing due to missing `./svelte-kit/tsconfig.json`
=> build: run svelte-kit sync in gh actions

package-lock.json, src/lib/components/account-menu/account-menu.svelte, src/lib/components/account-menu/components/account-menu-item.svelte, src/lib/components/button/button.svelte, src/lib/components/divider/divider.svelte, src/lib/components/flyout/flyout.svelte, src/lib/components/identity-badge/identity-badge.svelte, src/lib/stores/theme/theme.store.ts, src/routes/+layout.svelte, src/routes/settings/+page.svelte, src/routes/settings/components/setting.svelte
Quick PR to add the account menu as seen in the designs + a basic settings page implementation which is missing most advanced settings still.
Based on https://github.com/radicle-dev/drips-app-v2/pull/33 due to the new ability to set a `size` for `IdentityBadge` on this branch.
Resolves #34 and resolves #40 . We can add a network selector to the account menu once V2 is deployed to more than one testnet, and add the missing settings in follow-up PRs.
=> feat: account menu, settings page stub

src/lib/components/section-skeleton/section-skeleton.svelte
The section-skeleton component currently sets its own height to the height of the content at the moment `loaded` is true and `empty` is false, but doesn't update its height if its slot content changes afterwards (for example after creating a new stream which is now displayed in the streams section. This PR makes the section skeleton update its own height whenever a DOM mutation of its slot is observed.
=> fix: section-skeleton does not update height when content changes

src/routes/+layout.svelte, src/routes/+page.svelte
Adds a simple initial connect page.
Resolves #24
=> feat: simple connect page

src/lib/components/stepper/stepper.svelte
Resolves #51 
We were checking the height of `stepElement`, which is not always reliably equal to the current step due to an apparent bug (?) in Svelte with `bind:this` on transitioned elements. Checking the height of `observedElement` instead appears to fix the problem.
=> fix: quick promises break stepper height

src/lib/components/drips-animation/drips-animation.svelte
Resolves #50 
- Limit amount of drips on screen based on width of the animation (less drips on mobile)
- Avoid fractional pixel draws by rounding coordinates
- Limit max resolution multiplier to 2
=> fix: poor performance of drip animation

.gitignore, package-lock.json, package.json
Adds c8 coverage report dep so we can run `npm run coverage` locally and in CI.
=> test: add c8 coverage report dep

src/lib/stores/streams/methods/build-asset-configs.ts
There was a bug if an asset config was updated while already out of funds, resulting in the UI estimating a negative outbound balance for the given asset. This fixes that.
=> fix: negative outbound balance estimation in some situations

src/lib/components/table/table.svelte, src/lib/components/token-stat/token-stat.svelte, src/lib/components/tooltip/tooltip.svelte, src/routes/app/[userId]/tokens/[token]/+page.svelte, src/routes/app/dashboard/sections/balances.section.svelte
Adds explanatory tooltips for "Incoming" and "Outgoing" balance headers. Copy TBD
Resolves #80
=> feat: tooltip headers in balances section

src/lib/components/global-advisory/global-advisory.svelte, src/lib/components/header/header.svelte, src/lib/components/large-empty-state/large-empty-state.svelte, src/lib/stores/global-advisory/global-advisory.store.ts, src/lib/stores/wallet/wallet.store.ts, src/routes/app/+layout.svelte
Resolves #57
Adds a new "global-advisory" store, which can be used to show full-screen, blocking warnings, or a blue screen of death. Also replaces the blank screen while a wallet connection is restoring on first load with a spinner.
=> feat: global advisory store & app init loading state

src/lib/utils/format-token-amount.ts
Best I could come up with is this:
=> fix: negative amtPerSec smaller than max decimals shows up as -0

src/routes/+page.svelte
I think mobile works better now. the links section was just too wide. and updated the docs link to the v2 docs.
Signed-off-by: Brandon Oxendine <brandon.oxendine@gmail.com>
fixes #145
=> fix: Mobile fixed and docs link updated

src/lib/components/stepper/utils/transact.ts, src/lib/flows/collect-flow/collect-amounts.svelte, src/lib/flows/create-stream-flow/input-details.svelte, src/lib/flows/create-stream-flow/methods/create-stream.ts, src/lib/flows/delete-stream-flow/confirm.svelte, src/lib/flows/delete-stream-flow/methods/delete-stream.ts, src/lib/flows/edit-splits-flow/edit-splits-inputs.svelte, src/lib/flows/edit-stream-flow/enter-new-details.svelte, src/lib/flows/pause-flow/pause.svelte, src/lib/flows/top-up-flow/approve.svelte, src/lib/flows/top-up-flow/trigger-top-up-transaction.svelte, src/lib/flows/unpause-flow/unpause.svelte, src/lib/flows/withdraw-flow/enter-amount.svelte
Introduces a new stepper utility `transact`, which standardises the "sign, wait for confirmation, update UI" pattern we're using in every flow that triggers a transaction. The utility supports multiple transactions too, which are triggered one after the other.
All this is in preparation for #273, and will make it a lot easier to make our app a full Safe App.
=> refactor: transact utility

src/lib/stores/streams/methods/build-asset-configs.ts
Fixes two issues:
- Paused, non-scheduled streams may show a completely wrong start date on the stream detail view.
- If a stream is created after the first DripsSetEvent for the given asset config, the app wrongly assumes that the stream had been paused since the very first DripsSetEvent ever published for the same asset config. Now, it only creates paused streams in an AssetConfig's history if the stream had existed ever before.
TODO: Test cases for both the above issues
Resolves #300 
Resolves #299
=> fix: wrong start date timestamp in some situations

src/lib/flows/create-stream-flow/input-details.svelte, src/routes/app/dashboard/sections/streams.section.svelte
When clicking "Create Stream" on a token page, the create stream modal now has the same token pre-selected, instead of always the first one in the tokens list.
resolves #296
=> feat: #296

src/lib/stores/streams/metadata.ts, src/routes/api/ipfs/pin/+server.ts
Locks down /api/ipfs/pin endpoint so that it can only be used for valid account metadata. Also now explicitly throws an error in user flows if pinning metadata fails for whatever reason.
=> fix: #95, fix: #130

src/lib/stores/balances/utils/estimate.ts
There was a typo here that caused streams to not be included in the current cycle estimate if they were created before the current cycle began.
=> fix: streams missing in current cycle estimate

src/lib/stores/modal/modal.store.ts
Prevents navigation away from page while a modal is open.
Resolves #329
=> feat: #329

src/lib/components/amount/amount.svelte, src/lib/components/carousel/items/edu-card.svelte, src/lib/components/section-header/section-header.svelte, src/lib/components/step-header/step-header.svelte, src/lib/components/stepper/stepper.svelte, src/lib/components/stepper/utils/transact.ts, src/lib/components/toggleable/toggleable.svelte, src/lib/flows/collect-flow/collect-amounts.svelte, src/lib/flows/collect-flow/collect-flow-state.ts, src/lib/flows/collect-flow/collect-flow-steps.ts, src/lib/flows/create-stream-flow/create-stream-flow-state.ts, src/lib/flows/create-stream-flow/create-stream-flow-steps.ts, src/lib/flows/create-stream-flow/input-details.svelte, src/lib/flows/edit-splits-flow/edit-splits-flow-state.ts, src/lib/flows/edit-splits-flow/edit-splits-flow-steps.ts, src/lib/flows/edit-splits-flow/edit-splits-inputs.svelte, src/lib/flows/edit-stream-flow/edit-stream-flow-state.ts, src/lib/flows/edit-stream-flow/edit-stream-flow-steps.ts, src/lib/flows/edit-stream-flow/enter-new-details.svelte, src/lib/flows/top-up-flow/enter-amount.svelte, src/lib/flows/top-up-flow/top-up-flow-state.ts, src/lib/flows/top-up-flow/top-up-flow-steps.ts, src/lib/flows/withdraw-flow/enter-amount.svelte, src/lib/flows/withdraw-flow/withdraw-flow-state.ts, src/lib/flows/withdraw-flow/withdraw-flow-steps.ts, src/lib/utils/restorer.ts
Automatically saves & restores form inputs within stepper flows after coming back to a step (e.g. after an error or declining a transaction and clicking "try again")
Resolves #192
=> feat: save & restore input values in all flows

src/lib/components/account-menu/account-menu.svelte, src/lib/components/beta-badge/beta-badge.svelte, src/lib/components/header/header.svelte, src/lib/stores/scroll/scroll.store.ts, src/routes/+page.svelte, src/routes/components/lp-header.svelte, src/routes/legal/+layout.svelte, src/routes/legal/access/+page.svelte, src/routes/legal/disclaimer/+page.svelte, src/routes/legal/longform-text.css, src/routes/legal/privacy/+page.svelte
Includes
- new beta badge next to LP header drips logo
- adjusted beta notice copy on LP
- links back to Drips v1 in LP beta notice, footer
- new /legal/privacy, /legal/access and /legal/disclaimer pages
- links to legal pages in LP footer and account menu
=> feat: soft launch adjustments

src/lib/components/banner/banner.svelte, src/lib/components/illustrations/drips-v1-logo.svelte, src/routes/app/[userId]/+page.svelte
Adds a dismissable "looking for drips v1?" card at the bottom of profiles that allows quickly opening the current profile on Drips V1.
=> feat: show "back to drips v1" card on profiles

package-lock.json, package.json
Removing this dep since we don't critically rely on it and it's blocking resolving a minor security advisory. We can bring back coverage reporting later by upgrading `vitest` and installing the `@vitest/coverage-v8` package.
=> chore: remove @vitest/coverage-c8

src/lib/components/developer-section/developer.section.svelte, src/lib/stores/developer-mode/developer-mode.store.ts, src/routes/app/(app)/[accountId]/+page.svelte, src/routes/app/(app)/drip-lists/[listId]/+page.svelte, src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte, src/routes/app/(app)/settings/+page.svelte
Adds a new "Developer mode" toggle to settings (default off) that shows a new "Developer" section on address profiles, project profiles and drip lists, which allows easily seeing and copying account IDs. Can add more info here later.
=> feat: developer mode

src/lib/components/drip-list-card/drip-list-card.svelte, src/lib/components/identity-badge/identity-badge.svelte, src/lib/components/pile/pile.svelte, src/lib/components/user-avatar/user-avatar.svelte
closes #644
added a big focus-visible:ring to linked IdentityBadge when it's just showing just Avatar
=> make avatars on drip-list-card clickable (closes #644)

src/lib/components/splits-table/splits-table.svelte, src/lib/components/token-stat/token-stat.svelte, src/routes/app/(app)/[accountId]/tokens/[token]/streams/[dripId]/+page.svelte, tailwind.config.cjs
closes #655
note some new proposed headers in the footer
note "Starts/Started" appears higher, and no need for "Created" since same date as started
=> stream progress bar better mobile (vertical), re-label small stats (closes #655)

src/lib/components/aggregate-fiat-estimate/aggregate-fiat-estimate.svelte, src/lib/components/aggregate-fiat-estimate/fiat-estimate-value.svelte, src/lib/components/annotation-box/annotation-box.svelte, src/lib/components/button/button.svelte, src/lib/components/pile/pile.svelte, src/lib/components/token-amounts-table/token-amounts-table.svelte, src/lib/components/unclaimed-project-card/unclaimed-project-card.svelte, src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte, src/routes/app/(flows)/claim-project/steps/enter-git-url/enter-git-url.svelte
- reflow to fit inside screen
- "claim" button above the fold
- shorten the AnnotationBox text at the top so things aren't pushed down
Projects Dashboard collectable tokens table:
=> style: improve claimable funds section on project profile on mobile

src/e2e-tests/top-up-create-stream.e2e.test.ts, src/lib/flows/edit-drip-list/steps/edit-drip-list.svelte
problem: the drip list editor was bound to the `dripList` variable, but the submit function used `items` and `percentages`, which are just the original values passed in as props from the parent. Thus, any changes made to `dripList` by the editor didn't actually get applied fully.
Also made sure the E2E suite catches this in the future.
=> fix: existing drip list editor broken

src/lib/utils/fiat-estimates/fiat-estimates.ts
If all tokens are unknown, don't call the `/price` without any IDs, because it's just a 404 and creates an unnecessary unhandled exception.
=> fix: fiat estimate makes useless price call if no known tokens

src/lib/components/stepper/stepper.svelte, src/routes/+page.svelte, src/routes/app/(flows)/funder-onboarding/+page.svelte, src/routes/app/(flows)/funder-onboarding/steps/build-list/build-list.svelte
Imo best to revert this for now:
- user could be linked to this flow from anywhere, including external sites, in which case it's weird to have an on-page back button. we'd have no idea where it leads to
- if you enter the URL directly or get linked from an external app (e.g. Discord), there's a "back" button, but it just doesn't do anything
- the flow isn't being "concluded", so i don't think dispatching the `conclude` event is appropriate
We should rather work on putting this flow into a modal and being able to trigger it from anywhere soon IMO. Wdyt?
=> Revert "fix: add back button to funder flow, first step (#666)"

.husky/pre-commit
IMO there are a few workflow problems with this:
- It runs the check on the entire repo, not just on your staged changes (like the linter does), so you are blocked from committing a perfectly valid change if you have any in-progress unstaged changes elsewhere in the repo that svelte-check doesn't like.
- It practically makes the VSCode commit button useless, at least on my macbook — takes anywhere between 30 seconds to 1 minute to commit. It's a bit better, but still pretty slow on the terminal, especially if you're making many commits in a row.
- If your workflow is to make a lot of changes, and then selectively stage & commit to break them into multiple chunks, you now have to wait for `svelte-check` to scan the entire repo for _every_ individual commit, even if you already ran …
=> Revert "Add svelte check in pre-commit hook"

src/e2e-tests/top-up-create-stream.e2e.test.ts, src/lib/components/annotation-box/annotation-box.svelte, src/lib/flows/collect-flow/collect-amounts.svelte, src/lib/flows/collect-flow/collect-flow-state.ts, src/lib/flows/collect-flow/fetch-collectable-amounts.svelte, src/lib/utils/format-date.ts, src/routes/app/(app)/projects/+page.svelte
Most users will only be collecting split income (from Drip Lists and Projects), so this aims to simplify their collect screen by hiding most streaming-related stuff.
- Completely hides streaming-related balances if they're zero
- Hides squeezing if they're zero
- Greatly simplifies language around collectable balances — no more "cycle", no more "splittable", etc.… just "settlement once per week".
Also:
- Fix for `AnnotationBox` having a wonky layout if actions slot is empty (cc @evvvritt)
Someone who is collecting income from Drip Lists / Projects & also has some stream income now sees the screen like this:
=> feat: simplified collect screen

src/lib/components/drip-list-editor/drip-list-editor.svelte, src/lib/components/support-card/support-card.svelte, src/lib/flows/edit-drip-list/edit-drip-list-steps.ts, src/lib/flows/edit-drip-list/steps/edit-drip-list.svelte, src/lib/stores/wallet/network.ts, src/routes/app/(app)/drip-lists/[listId]/+page.svelte, src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte, src/routes/app/(flows)/funder-onboarding/steps/build-list/build-list.svelte
=> feat: drip list support button

src/lib/components/drip-list-badge/drip-list-badge.svelte, src/lib/components/splits/components/split/split.svelte, src/lib/components/table/cells/user-badge.cell.svelte, src/routes/app/(app)/[accountId]/tokens/[token]/streams/[dripId]/+page.svelte, src/routes/app/(app)/streams/sections/streams.section.svelte, src/routes/app/(flows)/funder-onboarding/funder-onboarding-flow.ts
closes #700 (don't see a reason not to just merge this into main?)
(would've been nice to hide the drip list username when in dashboard streams context but seems really hairy to pass that context down to the UserBadgeCell component?)
=> style: use drip-list-badge in streams table (closes #700)

src/lib/flows/top-up-flow/enter-amount.svelte
=> style: rmv 'funds' in Add modal (closes #719)

.github/workflows/check.yml, .github/workflows/commitlint.yml, .github/workflows/e2e-tests.yml, .github/workflows/unit-tests.yml
Speeds up `npm ci` in GitHub actions a lil. We could get it to be much faster if we remove the install scripts in the drips SDK and `radicle-design-system` packages.
=> ci: cache npm deps

package.json, scripts/install-design-system-static-assets.sh
Just removes the leftover font asset script, after #710
=> fix: untracked old otf inter fonts appear after every npm install

src/lib/components/drip-list-card/drip-list-card-representational.svelte, src/lib/components/drip-lists-section/drip-lists-section.svelte, src/lib/components/splits/components/split/split.svelte, src/lib/components/splits/splits.svelte, src/lib/components/text-expandable.svelte/text-expandable.svelte, src/lib/components/transitioned-height/transitioned-height.svelte, src/routes/app/(app)/+layout.svelte
Makes the drip list "thumb" card layout stable while loading, and neatly interpolates the height of the splits on the single drip list view:
https://github.com/drips-network/app/assets/1018218/ff92b52b-e5f4-4788-bcd3-186acd4bf9dc
Caveat is that this no longer shows list descriptions in listing contexts… Which I think is probably fine, since they still exist when viewing a single drip list directly. If we definitely want to show them, we could:
1. Show max a single truncated line of description, in a container exactly as high as one row in the splits component 
2. reduce the max rows in the split component for drip lists card w/ description by 1
… then the height would still remain stable. Wdyt?
=> feat: stable drip lists view

src/routes/app/(app)/drip-lists/+page.svelte, src/routes/app/(app)/streams/+page.svelte
I took a guess that this is the docs page intended to be linked to:
https://docs.drips.network/support-your-dependencies
=> Fixes dead links.

src/lib/components/button/button.svelte, src/lib/components/code-box/code-box.svelte, src/routes/+page.svelte, src/routes/app/(app)/projects/+page.svelte, src/routes/components/lp-header.svelte
- refactor Button.svelte to allow being `<a>` tag so the focus/hover state is consistent.
- apply to new, more prominent "Add to your repo" button in the Funding.json codebox (#507)
=> Button.svelte can be a link/<a>, apply to CodeBox (closes #507)

src/lib/components/button/button.svelte, src/routes/+page.svelte, src/routes/app/(app)/projects/+page.svelte
`<Button />`'s in support card weren't full width after #804
=> fix: Button should be inline-block display

src/lib/components/bottom-nav/bottom-nav.svelte, src/lib/components/header/header.svelte, src/lib/components/highlight/highlight.svelte, src/lib/components/sidenav/components/sidenav-item.svelte, src/lib/stores/highlight/highlight.store.ts, src/routes/app/(app)/component-showcase/+page.svelte, src/routes/app/(app)/drip-lists/+page.svelte, src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte, src/routes/app/(flows)/claim-project/steps/success/success.svelte, src/routes/app/+layout.svelte
Adds a store that can be used to globally "highlight" any element on the page, and implements a highlight of the "projects" tab right after claiming a project.
https://discord.com/channels/1096003917717983252/1096004153085530253/1172144860430618695
=> feat: highlight store, highlight projects tab for earnings after claiming project

package.json, src/e2e-tests/helpers/environment.ts, src/e2e-tests/top-up-create-stream.e2e.test.ts
No longer runs docker compose up as part of the test script. Instead, the npm run e2e command now executes docker-compose up ahead of running the test script. This makes it faster (because the docker-compose services can already start while it's building the app), and also allows running the e2e script within the drips graphQL repo, where a different docker environment is required.
=> ci: run docker-compose outside of e2e script

src/lib/components/supporters-section/supporters.section.svelte, src/routes/app/(app)/drip-lists/[listId]/+page.svelte, src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte
Fixes wrong support amounts in support section. Examples below are ethers.
Before:
After:
Resolves #871
=> fix: wrong support amounts

src/lib/components/project-avatar/project-avatar.svelte, src/routes/api/share-images/project/[projectUrl].png/+server.ts
The API should ever only return an emoji here, but best sanitize for good measure, because `twemoji.parse` preserves arbitrary HTML markup.
=> sanitize project emoji values for good measure

src/lib/components/percentage-editor/percentage-editor.svelte, src/lib/components/visual-percentage-editor/visual-percentage-editor.svelte
0% is allowed on the sliders so style as normal values:
so change this:
to this:
=> style: empty values in percentage editor as normal (not error/negative)

src/routes/external/[url]/+page.ts
It previously allowed everything except `javascript` protocol links. This restricts it further to only allow `http` and `https` links, to ensure absolutely no potentially funky things / app interactions with locally installed applications can be triggered.
=> only allow http and https protocols on external route

src/lib/components/project-profile-header/project-profile-header.svelte, src/lib/components/support-card/support-card.svelte, src/lib/utils/build-project-url.ts, src/routes/api/github/[repoUrl]/+server.ts, src/routes/api/github/[repoUrl]/redis.ts, src/routes/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte, src/routes/app/(app)/projects/(forges)/github/[githubUsername]/[githubRepoName]/+page.server.ts, src/routes/app/(app)/projects/(forges)/github/[githubUsername]/[githubRepoName]/+page.svelte
Adds additional handling for renamed repos, and incorrect casing (related to #856). Does NOT yet include full handling for deleted repos, because that will require some API work.
Changes:
- The server now sends a 301 redirect when "correcting" the casing or name (if repo renamed) of a Drips project, instead of just loading the "correct" project while keeping the URL untouched / wrong.
- Appending `?exact` to a project URL will disable the automatic redirection for project entirely. This makes it possible to view "outdated" old projects that still receive funds.
- Links to specific projects within the app (e.g. project cards on Projects tab, splits in project / drip list splits etc.) now include said `?exact` parameter, ensuring that you always go to the exact project that a split goes to …
=> handle project repo renames and incorrect casing

src/lib/components/aggregate-fiat-estimate/aggregate-fiat-estimate.svelte, src/lib/components/spinner/spinner.svelte, src/routes/+page.svelte, src/routes/app/(app)/component-showcase/+page.svelte, src/routes/components/lp-total-dripped-badge.svelte
(This PR should replace #725)
Adds "$ XXX,XXX dripped" counter to Landing Page using static values:
- Radworks USDC stream
- Radworks RAD stream
- Octant give
=> add 'total dripped' counter to landing page using static values (closes #645)

src/routes/api/redis.ts
Sometimes sockets closed unexpectedly, resulting in one-time error 500s. This should catch those errors while keeping the retry logic of the redis client.
=> catch redis errors

src/routes/api/share-images/project/[projectUrl].png/+server.ts
this PR updates the API route for project share images to properly handle custom image avatars. previously, the route only queried the deprecated emoji field for ClaimedProjects, resulting in missing custom avatars in share images. With this update:
- updated the API route to query the `avatar` field instead of the deprecated `emoji` field for `ClaimedProjects`.
- add necessary markup to display `ImageAvatars` if they exist
- tested the functionality locally for 3 cases: `custom avatars`, `emoji` & `default`
=> support custom avatars in dynamic project share images

src/lib/components/aggregate-fiat-estimate/aggregate-fiat-estimate.svelte, src/lib/components/drip-list-card/drip-list-card-representational.svelte, src/lib/components/supporters-section/components/support-item.svelte, src/lib/components/supporters-section/supporters.section.svelte
- Make the warnings when a token USD value is unknown grey instead of red (aka less intense)
- Remove the warning completely from drip list total amount fiat conversion includes unknown tokens (these tokens not listed on CMC likely don't any / much "real world value" anyway)
- Allow clicking on "Unknown token" in support table items (OTD & stream type) to bring up the "add custom token" modal with address pre-filled
=> improve unknown token handling

src/styles/elevation.css
restores proper border color, from
to
=> fix: elevation color should be foreground

src/lib/components/list-select/list-select.svelte
closes #901 
vertically align check-boxes/select-circles with content
=> fix: list-select checkbox vertical alignment

src/lib/components/step-layout/step-layout.svelte, src/lib/flows/edit-project-splits/steps/edit-dependency-list.svelte, src/lib/flows/edit-project-splits/steps/edit-maintainer-list.svelte, src/lib/flows/edit-project-splits/steps/review.svelte, src/lib/flows/edit-project-splits/steps/set-new-dependency-maintainer-split.svelte
closes #548, add's Cancel + Back buttons to Edit Project Splits flow like our other modals
=> fix: add back button to edit-project-splits (closes #548)

src/lib/components/drip-lists-section/drip-lists-section.svelte, src/lib/flows/create-drip-list-flow/create-drip-list-flow.ts, src/lib/flows/create-drip-list-flow/create-drip-list-stepper.svelte, src/lib/flows/create-drip-list-flow/steps/build-list/build-list.svelte
closes #1006 
- adds "Cancel" button to modal stepper (but not to funder onboarding)
=> fix: allow closing create-drip-list modal (closes #1006)

src/lib/components/large-empty-state/large-empty-state.svelte, src/routes/app/(app)/connect/+page.svelte
closes #958
also thought it nice to give them an option to decline and return to Explore? 
(though not quite sure why "secondary" buttons appear as first button in these large-empty-states?)
=> add connect button to connect-page (closes #958)

package-lock.json, package.json, src/lib/stores/tokens/additional-tokens.json, src/lib/stores/tokens/token-list.ts, src/lib/stores/tokens/tokens.store.ts, src/lib/stores/tokens/tokens.store.unit.test.ts
Updates default token list and adds a new `additional-tokens.json` file which we can use to manually add default tokens for the drips app on top of uniswap's default list.
Adds Glo Token, which is used by Funding the Commons.
Resolves #938
=> bump uniswap token list, add USDGLO

src/lib/utils/splits/get-split-percent.ts
If necessary, splits items now show up to two decimal places. Check the example below. Previously, all those split items would just say "1%".
Resolves #556
=> feat: display up to two decimal places in splits

src/lib/flows/create-stream-flow/input-details.svelte
It was possible to schedule a stream start & theoretically end dates because the check for the date being in the future was only applied on the date & time field levels, not on the overall combined date. Meaning that e.g. on the 1st of Jan at 1AM, you could schedule a stream to start on the 1st of Jan at midnight, and theoretically even end a second later.
Even though our estimation logic can handle it, this is strange, so this fixes it.
=> fix: possible to schedule stream in the past

src/lib/components/list-editor/components/list-editor-input.svelte, src/lib/utils/build-repo-url.ts
Resolves: https://github.com/drips-network/app/issues/1080
https://github.com/drips-network/app/assets/6360154/3cae3a0c-4044-43ce-aa03-b9e91662b451
=> refactor: allow Drips Projects URL as input in list editor

src/lib/components/input-address/input-stream-receiver.svelte, src/lib/flows/create-stream-flow/input-details.svelte, src/routes/app/(app)/[accountId]/tokens/[token]/streams/[dripId]/+page.svelte, src/routes/app/(app)/funds/sections/streams.section.svelte
Resolves: https://github.com/drips-network/app/issues/852
Also adds the ability to name streams to Drip Lists and fixes an issue that does not allow users to update a stream's name.
The only thing I am not really happy about is when you paste the Drip List URL while setting the stream receiver, it resolves directly to the Drip List ID. It might be a bit confusing but the card at the top of the modal showing the stream from => to clearly shows the resolved drip list name. Making it to resolve to something else by reusing what's already there and not introducing more changes, is not so easy, unless I am missing something. We can do it if needed, of course.
=> refactor: allow pasting Drip List URLs when setting streams

src/lib/components/drip-list-badge/drip-list-badge.svelte, src/lib/components/identity-badge/identity-badge.svelte, src/lib/stores/ens/ens.store.ts, src/lib/stores/ens/ens.store.unit.test.ts, src/lib/utils/decode-universal-account-id.ts, src/routes/app/(app)/[accountId]/tokens/[token]/+page.svelte, src/routes/app/+layout.svelte
Removes need to explicitly `connect` the `ens.store` with a provider. It just uses the `provider` from `wallet.store` now.
=> simplify ens store provider connection handling

src/lib/flows/global-collect-flow/steps/select-tokens/select-tokens.svelte, src/lib/stores/wallet/network.ts, src/lib/utils/settlement-date.ts
Allow customizing setllement date calculation and helper text per network, since different networks will settle on different cycles.
=> per network settlement information

src/lib/components/network-picker/components/network-list.svelte, src/lib/stores/wallet/network.ts, src/routes/app/(app)/[accountId]/+page.server.ts, src/routes/app/(app)/drip-lists/+page.ts, src/routes/app/(app)/drip-lists/all/+page.server.ts, src/routes/app/(app)/projects/(forges)/github/[githubUsername]/[githubRepoName]/+page.server.ts, src/routes/app/(app)/projects/+page.ts, src/routes/app/(app)/projects/all/+page.server.ts, src/routes/app/(app)/settings/+page.ts, src/routes/app/(app)/settings/custom-tokens/+page.ts
- Preserve URLs of address profiles, dashboard pages (drip lists, projects), project profiles, settings, and custom token settings when switching between networks
- Display all networks when app connected to testnet, only display mainnets if not
=> finalize network picker

src/lib/flows/claim-project-flow/steps/enter-git-url/enter-git-url.svelte, src/routes/api/github/[repoUrl]/+server.ts
Fixes an issue where it's impossible to claim funds for a project associated with a GH repo under different casing.
=> fix: unable to claim projects with wrong casing that have funds

src/lib/flows/claim-project-flow/claim-project-flow.ts, src/lib/flows/claim-project-flow/steps/add-ethereum-address/add-ethereum-address.svelte, src/lib/flows/claim-project-flow/steps/poll-api/poll-api.svelte
Currently, if the gasless owner update in the project claim flow fails to kick off (e.g. Gelato Relay down) or the task fails to conclude (e.g. we ran out of balance to sponsor gas with), the user is just left sitting on the "Waiting for verification to finalize..." screen while the app polls the API in anticipation of the owner updating. Which of course will never happen in those cases. This adds explicit checks for a successful gasless owner update call, and checks the task state on Gelato for failures. In both cases, the user will see "friendly" errors asking for them to either try again or reach out to us on Discord.
=> explicit errors if gasless owner update fails

src/lib/components/icons/Check.svelte, src/lib/components/icons/IconWrapper.svelte, src/lib/components/list-editor/components/list-editor-pie.svelte, src/lib/components/network-picker/components/network-list.svelte
Minor visual tweaks for network picker.
- Fixes unstyled text color for network picker in mobile account bottom sheet
- Fixes width of border outline for currently selected network
- Fixes color of checkmark icon
Resolves #1276
=> fix: #1276

robots-filecoin.txt
Adds new special robots.txt file for `filecoin.drips.network` deployment. It blocks indexing of everything except for everything under the `app/drip-lists` route. Once merged, the deploy script for `filecoin` app needs to be updated on Railway to copy this new robots.txt file to `/static/robots.txt`.
Resolves #1252
=> fix: #1252

src/lib/components/input-address/input-stream-receiver.svelte, src/lib/components/list-editor/components/list-editor-input.svelte, src/lib/components/list-editor/validators.ts, src/lib/components/search-bar/search.ts, src/lib/flows/create-drip-list-flow/steps/configure-voting-round/configure-voting-round.svelte, src/lib/stores/ens/ens.store.ts, src/lib/stores/wallet/__test__/wallet.store.ts, src/lib/stores/wallet/network.ts, src/routes/app/(app)/[accountId]/+page.server.ts
Adds new `ensSupported` value to static network config. If `false`, hides prompts to enter ens names in various places (stream creation modal, csv import) and stops treating `.eth` strings in address inputs as valid, and also stops trying to lookup ens names generally. Ensures attempts to load a profile by ens name results in a 404, and also removes `.eth` search results in search. Any attempts to `resolve` or `reverseLookup` an ens name from `ens.store` will result in `undefined`, and no longer throw an "ens not supported" error from Ethers.
Resolves #1233
=> fix: #1233

src/lib/components/annotation-box/annotation-box.svelte, src/lib/components/annotation-box/custodial-warning.svelte, src/lib/components/drip-list-editor/drip-list-editor.svelte, src/lib/flows/claim-project-flow/steps/configure-dependencies/configure-dependencies.svelte, src/lib/flows/claim-project-flow/steps/configure-maintainers/configure-maintainers.svelte, src/lib/flows/create-drip-list-flow/steps/build-list/build-list.svelte, src/lib/flows/create-drip-list-flow/steps/configure-voting-round/configure-voting-round.svelte, src/lib/flows/edit-project-splits/steps/edit-dependency-list.svelte, src/lib/flows/edit-project-splits/steps/edit-maintainer-list.svelte, src/lib/flows/vote/vote.svelte
This PR adds a warning for eth address entry situations telling the user to add only self-custodial addresses.
=> 1295 add a warning not to send funds to exchange managed addresses

src/lib/flows/create-stream-flow/input-details.svelte, src/lib/flows/delete-stream-flow/confirm.svelte, src/lib/flows/edit-drip-list/shared/steps/edit-drip-list.svelte, src/lib/flows/edit-project-metadata/steps/set-new-metadata.svelte, src/lib/flows/edit-project-splits/steps/review.svelte, src/lib/flows/edit-stream-flow/enter-new-details.svelte, src/lib/utils/ipfs.ts
Resolves https://github.com/drips-network/app/issues/1383, and this bug: https://github.com/drips-network/app/issues/1382
=> integrate new last processed ipfs hash field when awaiting on account metadata update

src/lib/components/code-box/code-box.svelte, src/lib/flows/claim-project-flow/claim-project-flow.ts, src/lib/flows/claim-project-flow/steps/add-ethereum-address/add-ethereum-address.svelte, src/lib/flows/claim-project-flow/steps/add-ethereum-address/drips-json-template.ts, src/lib/flows/claim-project-flow/steps/connect-wallet/connect-wallet.svelte, src/lib/flows/claim-project-flow/steps/enter-git-url/enter-git-url.svelte, src/lib/flows/claim-project-flow/steps/enter-git-url/enter-git-url.ts, src/lib/utils/github/GitHub.ts, src/lib/utils/insert-text-at-indicies.ts, src/styles/typography.css
This PR accommodates `FUNDING.json`s that already have content during the claim process. If they have content, a "diff" is shown, demonstrating what to add to the file.
=> 1329 when already a fundingjson present propose editing it instead of creating

src/lib/flows/claim-project-flow/claim-project-flow.ts, src/lib/flows/claim-project-flow/steps/configure-dependencies/configure-dependencies.svelte, src/lib/flows/claim-project-flow/steps/configure-maintainers/configure-maintainers.svelte, src/lib/flows/create-drip-list-flow/steps/build-list/build-list.svelte, src/lib/flows/edit-project-splits/edit-project-splits-steps.ts, src/lib/flows/edit-project-splits/steps/edit-dependency-list.svelte, src/lib/flows/edit-project-splits/steps/edit-maintainer-list.svelte, src/lib/flows/import-from-csv/import-from-csv-steps.ts, src/lib/utils/github/GitHub.ts
This PR brings changes to allow users to edit their maintainers and dependencies by uploading a CSV file. It also brings the same to the project claim process. It fixes an issue where a cached version of the FUNDING.json would be returned during verification instead of the updated on.
**Flows Updated**
Claim Project
* Configure dependencies
* Configure maintainers
Edit project splits
* Edit dependency list
* Edit mantainters list
=> 1102 populate maintainer dependency splits for projects from csv

src/lib/flows/claim-project-flow/steps/add-ethereum-address/drips-json-template.ts
This PR fixes a bug with the highlighting of additional FUNDING.json stanzas that happen to already exist in the source.
Given this existing FUNDING.json:
Produces:
=> Highlighted section incorrect for claim on further networks

src/lib/components/list-editor/classifiers.ts, src/lib/components/list-editor/validators.ts
This PR ensures that Github repo identifiers are properly capitalised when loaded. 
Test Input:
```csv
recipient,percentage
0x79756b6C2f913271fc0ee29A877fbd98258972BF,20
https://github.com/celtd/voting_mechanism_design,20
https://github.com/celtd/builtin-actors,20
```
=> CSV import capitalization correction doesn't (always?) appear to be working

src/lib/utils/__test__/calc-salt.unit.test.ts, src/lib/utils/calc-salt.ts, src/lib/utils/driplist/DripListService.ts
Removes the count of Drip Lists when determining a salt for a new Drip List.
=> Generate a random Drip List ID when creating a new Drip List

src/lib/components/projects-section/projects-section.svelte
Previously, the /projects route would show the empty state if you had _only_ hidden projects, and wouldn't allow displaying those.
=> fix empty state of projects section if all projects hidden

src/lib/utils/filter-falseish.ts, src/lib/utils/filter-falsy.ts, src/routes/(pages)/app/(app)/+page.server.ts, src/routes/(pages)/app/(app)/components/default-explore-page.svelte, src/routes/(pages)/app/(app)/components/distribution-explore-page.svelte, src/routes/(pages)/app/(app)/components/drip-lists-grid.svelte, src/routes/(pages)/app/(app)/components/load-distribution-explore-page-data.ts, tsconfig.json
Removes the right-hand single featured list on the distribution explore page variant and replaces it with the standard "Featured Drip Lists" section.
Features both RGPF distribution lists on Filecoin that exist at the moment.
=> add featured lists section to distribution explore page, feature 2nd round of FIL distribution

.dockerignore, Dockerfile.dev, docker-compose.yml, docker/dev-entrypoint.sh, docker/start-dev.sh, docker/start-e2e.sh, scripts/build-gql-types.sh
`.svelte-kit` dir, which includes dynamically created types for development (such as route params, page data types etc.) was being mounted in the dev container as an anonymous volume, causing it to not be written on the host. This means that types would never by updated during dev unless runing the dev server or svelte-kit sync on the host, outside of Docker.
This makes it so that the dev server running within Docker also updates the .svelte-kit dir on the host.
It also adds logic for always running the dev server as the same user that ran `npm run dev:docker` to fix permission issues.
Also adds an ASCII `GM` log 🌈
=> fix dev server not updating sk dev types

src/lib/stores/tokens/additional-tokens.json, src/lib/stores/tokens/tokens.store.ts, src/lib/stores/tokens/tokens.store.unit.test.ts
Lots of activity for this token on Drips so finally adding it as a default token, so ppl no longer need to add it to their custom tokens to see it.
Also adds logic for clearing the stored custom tokens of any tokens that are now part of the default list.
cc @nya-elimu
=> add elimu.ai token to default tokens

.dockerignore, Dockerfile.dev, docker-compose.dev.yml, docker-compose.e2e.yml, docker-compose.yml, docker/e2e-entrypoint.sh, docker/sprinkle.sh, docker/start-e2e.sh, docs/DEVELOPMENT.md, package.json, src/lib/components/date-picker/DateInput.svelte, src/lib/components/list-editor/components/list-editor-input.svelte, src/lib/components/text-input/text-input.svelte, src/lib/graphql/dripsQL.ts, src/lib/utils/get-optional-env-var/access-optional-env-var.ts, tests/claim-project.spec.ts, tests/create-drip-list.spec.ts
Fixes a bug with the local docker env where testnet chain state would not be persisted between runs of the local env.
Also adds `npm run dev:docker:sprinkle` command, which runs `sprinkler` against the local env. This can be used for full e2e test including making donations & collecting earnings later.
also adds (basic) specs for creating drip lists (normal & collaborative)
AND ALSO it now runs the headless tests against a real production build of the app, rather than dev server.
=> sprinkler in dev env, fix testnet data retention, create drip list test, run headless tests against prod build

src/lib/flows/create-donation/methods/create-donation.ts
suppress wallet warnings for high ERC-20 approvals during otd flow by only asking for necessary allowance
=> ask to approve only necessary amount for OTD

src/lib/flows/create-donation/input-details.svelte, src/lib/flows/create-donation/methods/create-donation.ts
Makes it so that one-time donations immediately appear on a drip list / project page after being sent, no need to manually refresh
=> automatically refresh supporters section after OTD

src/lib/components/stepper/components/transact-step.svelte
Triggers an `await-error-step` if the `before` fn on a `transact` step fails. This allows the user to see the error and retry. Before this, it would simply stay on this step loading forever without any indication of an error.
=> fix: #1439

src/routes/(pages)/app/(app)/projects/(forges)/components/project-profile/project-profile.svelte
state the network name in "unclaimed" note on project profile to reduce confusion re. multichain
=> fix: #1419

src/lib/utils/FailoverJsonRpcProvider.ts, src/routes/api/health/+server.ts
improve the /api/health endpoint with additional checks:
- RPC provider successfully returns latest block
- explore page loads
- LP loads
- gqlApi responds
also sets a 10s max timeout before FailoverJsonRpcProvider will abort & retry with backup RPC.
=> improve health endpoint

src/hooks.server.ts
SvelteKit already logs unexpected uncaught errors to the console by default. We don't need to log all errors, as this will cause e.g. 404s to result in a large trace being printed to console.
Also removes the Sentry integration (temporalily?) as we don't use it ATM.
=> remove excessive error logs

src/routes/(pages)/(lp)/components/lp-footer.svelte
Found this small typo while looking at your cool project.
=> Fix typo in footer for the github repository

src/lib/components/rpgf-application-splits-card/rpgf-application-splits-card.svelte, src/lib/components/splits/types.ts, src/routes/(pages)/app/(app)/rpgf/rounds/[slugOrId]/applications/[id]/+page.svelte, src/routes/(pages)/app/(app)/rpgf/rounds/[slugOrId]/applications/[id]/shared/fetch-project-for-application.ts
Filecoin requested being able to see splits for a linked project on its application view
=> add splits to application view

src/lib/components/drip-list-card/methods/get-supporters-pile.ts, src/lib/components/project-avatar/project-avatar.svelte, src/lib/components/search-bar/components/result.svelte
and more stringently links types to the components used to render the piles.
[staging link to affected project](https://drips-mainnet-app-staging.up.railway.app/app/projects/github/Byron/gitoxide?exact)
=> Fix borked project icons in supporter piles
